name: fetch-all-roles

on:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: touch
      run: date +%s > last_updated
    - name: push
      uses: actions-x/commit@v1
