name: Release

on:
  push:
    tags: 
      - 2*

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2 
    - name: get date time as DTIME
      id: dtime
      run: echo "::set-output name=DTIME::$(date +'%Y-%m-%d-%H-%M-%S')"
    - name: push
      uses: actions-x/commit@v1
    - name: create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.dtime.outputs.DTIME }}
        release_name: Release ${{ steps.dtime.outputs.DTIME }}
        body: |
          GCP IAM Roles Updated as of: ${{ steps.dtime.outputs.DTIME }}
        draft: false
        prerelease: false
